// src/lib/locationRoles.js
// Exports the LOCATION_ROLES object for use in game logic

// Define production and development environments
const isLocalhost = process.env.NODE_ENV === "development";

// Locations already played in testing
const PLAYED_LOCATIONS = {
  "Cricket Stadium": [
    "Team Captain",
    "Head Coach",
    "Fast Bowler",
    "Spin Bowler",
    "Wicket Keeper",
    "Cricket Commentator",
    "Pitch Curator",
    "Team Doctor",
    "Fielding Coach",
    "Video Analyst",
    "Stadium Manager",
    "Groundsman",
    "Scoreboard Operator",
    "Security Head",
  ],

  "Local Railway Station": [
    "Station Master",
    "Ticket Collector",
    "Tea Vendor",
    "Railway Police",
    "Platform Inspector",
    "Food Stall Owner",
    "Coolie/Porter",
    "Cleaning Supervisor",
    "Announcement Officer",
    "Signal Operator",
    "Booking Clerk",
    "Railway Engineer",
    "Luggage Office Staff",
    "Medical Room Staff",
  ],

  Hospital: [
    "Chief Doctor",
    "Head Nurse",
    "Pharmacist",
    "Lab Technician",
    "Reception Manager",
    "Ambulance Driver",
    "Ward Assistant",
    "Radiologist",
    "Physiotherapist",
    "Security Guard",
    "Dietitian",
    "Blood Bank Officer",
    "ICU Specialist",
    "Hospital Administrator",
  ],

  "Five Star Hotel": [
    "General Manager",
    "Executive Chef",
    "Concierge",
    "Spa Manager",
    "Restaurant Host",
    "Housekeeping Head",
    "Valet Parking Staff",
    "Front Office Manager",
    "Bellboy",
    "Food & Beverage Director",
    "Room Service Staff",
    "Event Coordinator",
    "Pool Lifeguard",
    "Hotel Security",
  ],

  "Local Market": [
    "Vegetable Vendor",
    "Fruit Seller",
    "Spice Merchant",
    "Flower Shop Owner",
    "Street Food Vendor",
    "Jewelry Shop Owner",
    "Market Inspector",
    "Cloth Merchant",
    "Mobile Shop Owner",
    "Wholesale Dealer",
    "Cart Puller",
    "Tea Shop Owner",
    "Local Police",
    "Market Association Head",
  ],
  "Temple Complex": [
    "Head Priest",
    "Temple Administrator",
    "Prasad Distributor",
    "Devotional Singer",
    "Temple Guard",
    "Flower Garland Maker",
    "Donation Counter",
    "Temple Trustee",
    "Kitchen Manager",
    "Maintenance Staff",
    "Gift Shop Owner",
    "Shoe Stand Keeper",
    "Cleaning Staff",
    "Guide",
  ],
  "Shopping Mall": [
    "Mall Manager",
    "Store Owner",
    "Security Guard",
    "Food Court Chef",
    "Cinema Manager",
    "Maintenance Staff",
    "Customer Service Rep",
    "Parking Supervisor",
    "Housekeeping Head",
    "Display Designer",
    "Game Zone Operator",
    "HVAC Technician",
    "Lost & Found Staff",
    "Events Coordinator",
  ],
};

// New locations for production
const NEW_LOCATIONS = {
  "Yoga Ashram": [
    "Guru",
    "Meditation Teacher",
    "Ayurveda Doctor",
    "Kitchen Manager",
    "Yoga Instructor",
    "International Student",
    "Receptionist",
    "Grounds Keeper",
    "Accommodation Manager",
    "Local Guide",
    "Shop Keeper",
    "Security Guard",
    "Wellness Consultant",
    "Volunteer Coordinator",
  ],
  "IT Park": [
    "Startup Founder",
    "Software Architect",
    "Business Analyst",
    "Security Officer",
    "Cafeteria Manager",
    "Office Administrator",
    "Networking Engineer",
    "Cloud Specialist",
    "HR Recruiter",
    "Facility Manager",
    "UX Researcher",
    "Tech Support",
    "Data Scientist",
    "Meeting Room Coordinator",
  ],
  "Bollywood Set": [
    "Executive Producer",
    "Script Writer",
    "Spot Boy",
    "Dance Choreographer",
    "VFX Supervisor",
    "Casting Director",
    "Junior Artist Manager",
    "Dialogue Coach",
    "Set Decorator",
    "Production Controller",
    "Costume Designer",
    "Fight Master",
    "Music Composer",
    "Art Director",
  ],
  "Coaching Center": [
    "IIT Coach",
    "Mathematics Teacher",
    "Physics Expert",
    "Study Material Manager",
    "Career Counselor",
    "Admin Staff",
    "Computer Lab Technician",
    "Librarian",
    "Test Coordinator",
    "Accounts Manager",
    "Student Advisor",
    "Cafeteria Worker",
    "Security Guard",
    "Receptionist",
  ],
  "Beach Shack": [
    "Shack Owner",
    "Seafood Chef",
    "Bartender",
    "Water Sports Instructor",
    "Lifeguard",
    "Beach Cleaner",
    "Souvenir Seller",
    "Photographer",
    "Umbrella Rentals",
    "DJ",
    "Massage Therapist",
    "Tour Guide",
    "Boat Operator",
    "Security Guard",
  ],
  "Silk Saree Shop": [
    "Shop Owner",
    "Master Weaver",
    "Sales Manager",
    "Design Consultant",
    "Embroidery Expert",
    "Accounts Manager",
    "Display Artist",
    "Customer Service",
    "Alteration Specialist",
    "Quality Inspector",
    "Inventory Manager",
    "Traditional Expert",
    "Packaging Staff",
    "Security Guard",
  ],
  "Spice Factory": [
    "Factory Manager",
    "Quality Control",
    "Spice Blender",
    "Packaging Supervisor",
    "Machine Operator",
    "Storage Manager",
    "Lab Technician",
    "Export Coordinator",
    "Procurement Officer",
    "Maintenance Engineer",
    "Safety Inspector",
    "Loading Staff",
    "Accounts Manager",
    "Security Head",
  ],
  "Cricket Academy": [
    "Head Coach",
    "Batting Specialist",
    "Bowling Coach",
    "Fitness Trainer",
    "Equipment Manager",
    "Physiotherapist",
    "Mental Coach",
    "Video Analyst",
    "Nutrition Expert",
    "Ground Staff",
    "Admin Manager",
    "Junior Coach",
    "Front Desk",
    "Security Guard",
  ],
  "Meditation Center": [
    "Spiritual Guide",
    "Program Coordinator",
    "Meditation Teacher",
    "Kitchen Manager",
    "Accommodation In-charge",
    "Course Assistant",
    "Registration Staff",
    "Housekeeping Head",
    "Music Coordinator",
    "Bookstore Manager",
    "Maintenance Staff",
    "Garden Keeper",
    "Security Guard",
    "First Aid Staff",
  ],
  "Community Hall": [
    "Event Manager",
    "Catering Head",
    "Decoration Team Lead",
    "Sound Engineer",
    "Parking Supervisor",
    "Booking Coordinator",
    "Cleaning Supervisor",
    "Maintenance Staff",
    "Security Head",
    "Electrician",
    "Stage Manager",
    "Kitchen Staff",
    "Store Keeper",
    "Guest Relations",
  ],
};

// Combine locations based on environment
const LOCATION_ROLES = isLocalhost
  ? PLAYED_LOCATIONS
  : {
      ...PLAYED_LOCATIONS,
      ...NEW_LOCATIONS,
    };

export default LOCATION_ROLES;
